import AuthButton from "@/components/AuthButton/AuthButton";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/SessionProvider/SessionProvider";

export const metadata: Metadata = {
  title: "Sophisticated File Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body>
        <SessionProvider session={session}>
          <main>
            <AuthButton />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
